#!/usr/bin/env node
/**
 * AuraMarket Deployment Script
 * Deploys NFT and Marketplace contracts to Stellar Soroban Testnet
 * 
 * Usage: node scripts/deploy.js
 * Requires: stellar-cli installed, DEPLOYER_SECRET env var set
 */

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const NETWORK = "testnet";
const RPC_URL = "https://soroban-testnet.stellar.org";
const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";

const NFT_WASM = path.resolve(
  __dirname,
  "../target/wasm32-unknown-unknown/release/auramarket_nft.wasm"
);
const MARKETPLACE_WASM = path.resolve(
  __dirname,
  "../target/wasm32-unknown-unknown/release/auramarket_marketplace.wasm"
);

function exec(cmd) {
  console.log(`\n▶ ${cmd}\n`);
  return execSync(cmd, { encoding: "utf8", stdio: ["pipe", "pipe", "inherit"] }).trim();
}

function deployContract(wasmPath, name) {
  console.log(`\n══ Deploying ${name} ══`);

  // Upload WASM
  const uploadOutput = exec(
    `stellar contract deploy \
      --wasm ${wasmPath} \
      --source deployer \
      --network ${NETWORK} \
      --rpc-url ${RPC_URL} \
      --network-passphrase "${NETWORK_PASSPHRASE}"`
  );

  const contractId = uploadOutput.split("\n").pop().trim();
  console.log(`✓ ${name} deployed: ${contractId}`);
  return contractId;
}

async function main() {
  console.log("═══════════════════════════════════════");
  console.log("  AuraMarket — Soroban Testnet Deploy  ");
  console.log("═══════════════════════════════════════");

  // Verify WASM artifacts exist
  if (!fs.existsSync(NFT_WASM)) {
    console.error("NFT WASM not found. Run: cargo build --target wasm32-unknown-unknown --release");
    process.exit(1);
  }
  if (!fs.existsSync(MARKETPLACE_WASM)) {
    console.error("Marketplace WASM not found. Build contracts first.");
    process.exit(1);
  }

  // Get deployer address
  const deployerSecret = process.env.DEPLOYER_SECRET;
  if (!deployerSecret) {
    console.error("DEPLOYER_SECRET env var required");
    process.exit(1);
  }

  // Add key to stellar CLI
  exec(`stellar keys add deployer --secret-key ${deployerSecret}`);
  const deployerAddress = exec(`stellar keys address deployer`);
  console.log(`\nDeployer: ${deployerAddress}`);

  // Fund on testnet
  try {
    exec(`stellar keys fund deployer --network ${NETWORK}`);
    console.log("✓ Funded via Friendbot");
  } catch {
    console.log("(Friendbot skipped — account already funded)");
  }

  // Deploy NFT contract
  const nftContractId = deployContract(NFT_WASM, "AuraMarket NFT");

  // Initialize NFT contract
  console.log("\n── Initializing NFT contract ──");
  exec(
    `stellar contract invoke \
      --id ${nftContractId} \
      --source deployer \
      --network ${NETWORK} \
      --rpc-url ${RPC_URL} \
      --network-passphrase "${NETWORK_PASSPHRASE}" \
      -- initialize \
      --admin ${deployerAddress}`
  );
  console.log("✓ NFT contract initialized");

  // Deploy Marketplace contract
  const marketplaceContractId = deployContract(MARKETPLACE_WASM, "AuraMarket Marketplace");

  // Initialize Marketplace contract (fee = 250 bps = 2.5%)
  console.log("\n── Initializing Marketplace contract ──");
  exec(
    `stellar contract invoke \
      --id ${marketplaceContractId} \
      --source deployer \
      --network ${NETWORK} \
      --rpc-url ${RPC_URL} \
      --network-passphrase "${NETWORK_PASSPHRASE}" \
      -- initialize \
      --admin ${deployerAddress} \
      --nft_contract ${nftContractId} \
      --fee_bps 250`
  );
  console.log("✓ Marketplace contract initialized");

  // Write contract IDs to .env.local
  const envContent = `# Auto-generated by deploy.js — ${new Date().toISOString()}
NEXT_PUBLIC_NETWORK=testnet
NEXT_PUBLIC_RPC_URL=${RPC_URL}
NEXT_PUBLIC_NETWORK_PASSPHRASE=${NETWORK_PASSPHRASE}
NEXT_PUBLIC_NFT_CONTRACT_ID=${nftContractId}
NEXT_PUBLIC_MARKETPLACE_CONTRACT_ID=${marketplaceContractId}
NEXT_PUBLIC_DEPLOYER_ADDRESS=${deployerAddress}
`;

  fs.writeFileSync(path.resolve(__dirname, "../frontend/.env.local"), envContent);
  console.log("\n✓ Contract IDs written to frontend/.env.local");

  console.log("\n═══════════════════════════════════════");
  console.log("  Deployment Complete! 🎉");
  console.log("═══════════════════════════════════════");
  console.log(`  NFT Contract:         ${nftContractId}`);
  console.log(`  Marketplace Contract: ${marketplaceContractId}`);
  console.log(`  Network:              ${NETWORK}`);
  console.log("═══════════════════════════════════════\n");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
